# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rieon/Projects/personal/ali_ddns

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rieon/Projects/personal/ali_ddns

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rieon/Projects/personal/ali_ddns/CMakeFiles /Users/rieon/Projects/personal/ali_ddns/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rieon/Projects/personal/ali_ddns/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aliddns

# Build rule for target.
aliddns: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aliddns
.PHONY : aliddns

# fast build rule for target.
aliddns/fast:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/build
.PHONY : aliddns/fast

#=============================================================================
# Target rules for targets named cryptest

# Build rule for target.
cryptest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptest
.PHONY : cryptest

# fast build rule for target.
cryptest/fast:
	$(MAKE) -f thirdparty/cryptopp/CMakeFiles/cryptest.dir/build.make thirdparty/cryptopp/CMakeFiles/cryptest.dir/build
.PHONY : cryptest/fast

#=============================================================================
# Target rules for targets named cryptopp-static

# Build rule for target.
cryptopp-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptopp-static
.PHONY : cryptopp-static

# fast build rule for target.
cryptopp-static/fast:
	$(MAKE) -f thirdparty/cryptopp/CMakeFiles/cryptopp-static.dir/build.make thirdparty/cryptopp/CMakeFiles/cryptopp-static.dir/build
.PHONY : cryptopp-static/fast

#=============================================================================
# Target rules for targets named cryptest.exe

# Build rule for target.
cryptest.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptest.exe
.PHONY : cryptest.exe

# fast build rule for target.
cryptest.exe/fast:
	$(MAKE) -f thirdparty/cryptopp/CMakeFiles/cryptest.exe.dir/build.make thirdparty/cryptopp/CMakeFiles/cryptest.exe.dir/build
.PHONY : cryptest.exe/fast

#=============================================================================
# Target rules for targets named cryptopp-object

# Build rule for target.
cryptopp-object: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptopp-object
.PHONY : cryptopp-object

# fast build rule for target.
cryptopp-object/fast:
	$(MAKE) -f thirdparty/cryptopp/CMakeFiles/cryptopp-object.dir/build.make thirdparty/cryptopp/CMakeFiles/cryptopp-object.dir/build
.PHONY : cryptopp-object/fast

#=============================================================================
# Target rules for targets named dynamic

# Build rule for target.
dynamic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dynamic
.PHONY : dynamic

# fast build rule for target.
dynamic/fast:
	$(MAKE) -f thirdparty/cryptopp/CMakeFiles/dynamic.dir/build.make thirdparty/cryptopp/CMakeFiles/dynamic.dir/build
.PHONY : dynamic/fast

#=============================================================================
# Target rules for targets named static

# Build rule for target.
static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 static
.PHONY : static

# fast build rule for target.
static/fast:
	$(MAKE) -f thirdparty/cryptopp/CMakeFiles/static.dir/build.make thirdparty/cryptopp/CMakeFiles/static.dir/build
.PHONY : static/fast

#=============================================================================
# Target rules for targets named cryptopp-shared

# Build rule for target.
cryptopp-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptopp-shared
.PHONY : cryptopp-shared

# fast build rule for target.
cryptopp-shared/fast:
	$(MAKE) -f thirdparty/cryptopp/CMakeFiles/cryptopp-shared.dir/build.make thirdparty/cryptopp/CMakeFiles/cryptopp-shared.dir/build
.PHONY : cryptopp-shared/fast

#=============================================================================
# Target rules for targets named spdlog_headers_for_ide

# Build rule for target.
spdlog_headers_for_ide: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spdlog_headers_for_ide
.PHONY : spdlog_headers_for_ide

# fast build rule for target.
spdlog_headers_for_ide/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/spdlog_headers_for_ide.dir/build.make thirdparty/spdlog/CMakeFiles/spdlog_headers_for_ide.dir/build
.PHONY : spdlog_headers_for_ide/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ContinuousCoverage.dir/build.make thirdparty/spdlog/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ContinuousTest.dir/build.make thirdparty/spdlog/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ContinuousBuild.dir/build.make thirdparty/spdlog/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ContinuousStart.dir/build.make thirdparty/spdlog/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ExperimentalBuild.dir/build.make thirdparty/spdlog/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ExperimentalCoverage.dir/build.make thirdparty/spdlog/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ExperimentalSubmit.dir/build.make thirdparty/spdlog/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ContinuousUpdate.dir/build.make thirdparty/spdlog/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ExperimentalUpdate.dir/build.make thirdparty/spdlog/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ExperimentalStart.dir/build.make thirdparty/spdlog/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ContinuousSubmit.dir/build.make thirdparty/spdlog/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ExperimentalTest.dir/build.make thirdparty/spdlog/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/NightlySubmit.dir/build.make thirdparty/spdlog/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/NightlyMemCheck.dir/build.make thirdparty/spdlog/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ExperimentalConfigure.dir/build.make thirdparty/spdlog/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/NightlyCoverage.dir/build.make thirdparty/spdlog/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/NightlyTest.dir/build.make thirdparty/spdlog/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ContinuousMemCheck.dir/build.make thirdparty/spdlog/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/NightlyBuild.dir/build.make thirdparty/spdlog/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/NightlyConfigure.dir/build.make thirdparty/spdlog/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/NightlyUpdate.dir/build.make thirdparty/spdlog/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/NightlyMemoryCheck.dir/build.make thirdparty/spdlog/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ContinuousConfigure.dir/build.make thirdparty/spdlog/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/Nightly.dir/build.make thirdparty/spdlog/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/NightlyStart.dir/build.make thirdparty/spdlog/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/ExperimentalMemCheck.dir/build.make thirdparty/spdlog/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/Continuous.dir/build.make thirdparty/spdlog/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f thirdparty/spdlog/CMakeFiles/Experimental.dir/build.make thirdparty/spdlog/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named catch_tests

# Build rule for target.
catch_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 catch_tests
.PHONY : catch_tests

# fast build rule for target.
catch_tests/fast:
	$(MAKE) -f thirdparty/spdlog/tests/CMakeFiles/catch_tests.dir/build.make thirdparty/spdlog/tests/CMakeFiles/catch_tests.dir/build
.PHONY : catch_tests/fast

api.o: api.cpp.o

.PHONY : api.o

# target to build an object file
api.cpp.o:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/api.cpp.o
.PHONY : api.cpp.o

api.i: api.cpp.i

.PHONY : api.i

# target to preprocess a source file
api.cpp.i:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/api.cpp.i
.PHONY : api.cpp.i

api.s: api.cpp.s

.PHONY : api.s

# target to generate assembly for a file
api.cpp.s:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/api.cpp.s
.PHONY : api.cpp.s

config.o: config.cpp.o

.PHONY : config.o

# target to build an object file
config.cpp.o:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/config.cpp.o
.PHONY : config.cpp.o

config.i: config.cpp.i

.PHONY : config.i

# target to preprocess a source file
config.cpp.i:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/config.cpp.i
.PHONY : config.cpp.i

config.s: config.cpp.s

.PHONY : config.s

# target to generate assembly for a file
config.cpp.s:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/config.cpp.s
.PHONY : config.cpp.s

configuration.o: configuration.cpp.o

.PHONY : configuration.o

# target to build an object file
configuration.cpp.o:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/configuration.cpp.o
.PHONY : configuration.cpp.o

configuration.i: configuration.cpp.i

.PHONY : configuration.i

# target to preprocess a source file
configuration.cpp.i:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/configuration.cpp.i
.PHONY : configuration.cpp.i

configuration.s: configuration.cpp.s

.PHONY : configuration.s

# target to generate assembly for a file
configuration.cpp.s:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/configuration.cpp.s
.PHONY : configuration.cpp.s

crypto.o: crypto.cpp.o

.PHONY : crypto.o

# target to build an object file
crypto.cpp.o:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/crypto.cpp.o
.PHONY : crypto.cpp.o

crypto.i: crypto.cpp.i

.PHONY : crypto.i

# target to preprocess a source file
crypto.cpp.i:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/crypto.cpp.i
.PHONY : crypto.cpp.i

crypto.s: crypto.cpp.s

.PHONY : crypto.s

# target to generate assembly for a file
crypto.cpp.s:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/crypto.cpp.s
.PHONY : crypto.cpp.s

curl.o: curl.cpp.o

.PHONY : curl.o

# target to build an object file
curl.cpp.o:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/curl.cpp.o
.PHONY : curl.cpp.o

curl.i: curl.cpp.i

.PHONY : curl.i

# target to preprocess a source file
curl.cpp.i:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/curl.cpp.i
.PHONY : curl.cpp.i

curl.s: curl.cpp.s

.PHONY : curl.s

# target to generate assembly for a file
curl.cpp.s:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/curl.cpp.s
.PHONY : curl.cpp.s

ipchecker.o: ipchecker.cpp.o

.PHONY : ipchecker.o

# target to build an object file
ipchecker.cpp.o:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/ipchecker.cpp.o
.PHONY : ipchecker.cpp.o

ipchecker.i: ipchecker.cpp.i

.PHONY : ipchecker.i

# target to preprocess a source file
ipchecker.cpp.i:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/ipchecker.cpp.i
.PHONY : ipchecker.cpp.i

ipchecker.s: ipchecker.cpp.s

.PHONY : ipchecker.s

# target to generate assembly for a file
ipchecker.cpp.s:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/ipchecker.cpp.s
.PHONY : ipchecker.cpp.s

logger.o: logger.cpp.o

.PHONY : logger.o

# target to build an object file
logger.cpp.o:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/logger.cpp.o
.PHONY : logger.cpp.o

logger.i: logger.cpp.i

.PHONY : logger.i

# target to preprocess a source file
logger.cpp.i:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/logger.cpp.i
.PHONY : logger.cpp.i

logger.s: logger.cpp.s

.PHONY : logger.s

# target to generate assembly for a file
logger.cpp.s:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/logger.cpp.s
.PHONY : logger.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/main.cpp.s
.PHONY : main.cpp.s

urlencoder.o: urlencoder.cpp.o

.PHONY : urlencoder.o

# target to build an object file
urlencoder.cpp.o:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/urlencoder.cpp.o
.PHONY : urlencoder.cpp.o

urlencoder.i: urlencoder.cpp.i

.PHONY : urlencoder.i

# target to preprocess a source file
urlencoder.cpp.i:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/urlencoder.cpp.i
.PHONY : urlencoder.cpp.i

urlencoder.s: urlencoder.cpp.s

.PHONY : urlencoder.s

# target to generate assembly for a file
urlencoder.cpp.s:
	$(MAKE) -f CMakeFiles/aliddns.dir/build.make CMakeFiles/aliddns.dir/urlencoder.cpp.s
.PHONY : urlencoder.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... aliddns"
	@echo "... cryptest"
	@echo "... cryptopp-static"
	@echo "... cryptest.exe"
	@echo "... cryptopp-object"
	@echo "... dynamic"
	@echo "... static"
	@echo "... cryptopp-shared"
	@echo "... spdlog_headers_for_ide"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousStart"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalUpdate"
	@echo "... ExperimentalStart"
	@echo "... ContinuousSubmit"
	@echo "... ExperimentalTest"
	@echo "... NightlySubmit"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyTest"
	@echo "... ContinuousMemCheck"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyUpdate"
	@echo "... NightlyMemoryCheck"
	@echo "... ContinuousConfigure"
	@echo "... Nightly"
	@echo "... NightlyStart"
	@echo "... ExperimentalMemCheck"
	@echo "... Continuous"
	@echo "... Experimental"
	@echo "... catch_tests"
	@echo "... api.o"
	@echo "... api.i"
	@echo "... api.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... configuration.o"
	@echo "... configuration.i"
	@echo "... configuration.s"
	@echo "... crypto.o"
	@echo "... crypto.i"
	@echo "... crypto.s"
	@echo "... curl.o"
	@echo "... curl.i"
	@echo "... curl.s"
	@echo "... ipchecker.o"
	@echo "... ipchecker.i"
	@echo "... ipchecker.s"
	@echo "... logger.o"
	@echo "... logger.i"
	@echo "... logger.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... urlencoder.o"
	@echo "... urlencoder.i"
	@echo "... urlencoder.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

